import ReduxProvider from "@/lib/redux/reduxProvider";
import "@/styles/globals.css";
import { ToastContainer } from "react-toastify";
import { type Metadata } from "next";
import { Inter } from "next/font/google";
import TopLoader from "@/components/TopLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TopLoader />
          <ToastContainer />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
